// Generated by CoffeeScript 1.4.0
(function() {
  var Article, Storage, article, key, view, _i, _j, _len, _len1, _ref, _ref1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = ["angel-hide-hider", "angel-hide-sport"];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    key = _ref[_i];
    chrome.storage.sync.get(key, function(obj) {
      return console.log(key, obj);
    });
  }

  Article = (function(_super) {

    __extends(Article, _super);

    function Article() {
      this.render = __bind(this.render, this);

      this.key = __bind(this.key, this);

      this.toggleHideState = __bind(this.toggleHideState, this);

      this.initialize = __bind(this.initialize, this);
      return Article.__super__.constructor.apply(this, arguments);
    }

    Article.prototype.initialize = function() {
      var hidden, wrapper;
      wrapper = $('<div class="angel-wrapper"></div>');
      this.hider = $('<a href="#" >X</a>');
      this.$el.wrap(wrapper);
      this.$el.before(this.hider);
      hidden = !!Storage.get(this.key());
      if (hidden) {
        this.hider.click();
      }
      this.hider.click(this.toggleHideState);
      return this.render(hidden);
    };

    Article.prototype.toggleHideState = function() {
      var hidden;
      hidden = !Storage.get(this.key());
      Storage.set(this.key(), hidden);
      console.log("toggleHideState " + (this.key()) + " -> " + hidden);
      return this.render(hidden);
    };

    Article.prototype.key = function() {
      return "angel-" + this.$('a')[0].href;
    };

    Article.prototype.render = function(hidden) {
      this.$el.toggle(!hidden);
      return chrome.storage.sync.get("angel-hide-hider", function(obj) {
        if (obj["angel-hide-hider"]) {
          return this.hider.toggle(!hidden);
        }
      });
    };

    return Article;

  })(Backbone.View);

  Storage = {
    set: function(key, value) {
      try {
        return localStorage.setItem(key, value);
      } catch (error) {
        if (error.name === 'QUOTA_EXCEEDED_ERR') {
          localStorage.clear();
          return localStorage.setItem(key, value);
        } else {
          throw error;
        }
      }
    },
    get: function(key) {
      var value;
      value = localStorage.getItem(key);
      if (value === 'true') {
        return true;
      } else if (value === 'false') {
        return false;
      } else {
        return value;
      }
    },
    remove: function(key) {
      return localStorage.removeItem(key);
    }
  };

  _ref1 = $("li.inline-pic, li.pixie, li.mugshot");
  for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
    article = _ref1[_j];
    view = new Article({
      el: article
    });
  }

  chrome.storage.sync.get("angel-hide-sport", function(obj) {
    if (obj["angel-hide-sport"]) {
      return $("#sport-nwf-picks").hide();
    }
  });

}).call(this);
