// Generated by CoffeeScript 1.4.0
(function() {
  var options, restoreOptions, saveOptions;

  options = [["hide-sport", "angel-hide-sport"], ["hide-hider", "angel-hide-hider"]];

  saveOptions = function() {
    var id, key, select, setting, status, _i, _len, _ref;
    status = $("#status");
    for (_i = 0, _len = options.length; _i < _len; _i++) {
      _ref = options[_i], id = _ref[0], key = _ref[1];
      select = document.getElementById(id);
      setting = select.children[select.selectedIndex].value;
      chrome.storage.sync.set({
        key: setting
      });
      console.log(key, "->", setting);
    }
    status.append("Options Saved.");
    return setTimeout(function() {
      return status.text("");
    }, 5750);
  };

  restoreOptions = function() {
    var id, key, _i, _len, _ref, _results;
    _results = [];
    for (_i = 0, _len = options.length; _i < _len; _i++) {
      _ref = options[_i], id = _ref[0], key = _ref[1];
      _results.push(chrome.storage.sync.get(key, function(obj) {
        var child, select, setting, _j, _len1, _ref1, _results1;
        setting = obj[key];
        select = document.getElementById(id);
        _ref1 = select.children;
        _results1 = [];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          child = _ref1[_j];
          if (child.value === setting) {
            child.selected = "true";
            break;
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      }));
    }
    return _results;
  };

  document.addEventListener('DOMContentLoaded', restoreOptions);

  document.querySelector('#save').addEventListener('click', saveOptions);

}).call(this);
